#Change these settings to customize the server-side behavior of the mod.
["Travel Settings"]
	#Allow fish to go through the tubes. (experimental)
	allowFishTravel = true
	#Allow villagers to go through the tubes.
	allowVillagerTravel = true
	#Multiplier for the speed of the tubes. Default is 1.0, which is normal speed. (THIS IS HIGHLY EXPERIMENTAL)
	# Default: 1.0
	# Range: 0.5 ~ 99.0
	speedMultiplier = 1.0

#Stress Settings
["Stress Settings"]
	#Stress impact of the Hyper Entrance block.
	# Default: 4.0
	# Range: 0.0 ~ 100.0
	entranceStressImpact = 4.0
	#Stress impact of the Hyper Accelerator block.
	# Default: 4.0
	# Range: 0.0 ~ 100.0
	acceleratorStressImpact = 4.0
