[Misc]
	#Defines percentage brackets of spell level to corresponding rarity, ie first 30% of spell levels are common.
	#rarityConfig array values must sum to 1: [COMMON, UNCOMMON, RARE, EPIC, LEGENDARY]. Default: [.3d, .25d, .2d, .15d, .1d]
	rarityConfig = [0.3, 0.25, 0.2, 0.15, 0.1]
	#Whether or not imbued weapons require mana to be casted. Default: true
	swordsConsumeMana = true
	#The multiplier on the cooldown of imbued weapons. Default: 0.5 (50% of default cooldown)
	swordsCooldownMultiplier = 0.5
	#Whether or not players can harm their own magic summons. Default: false
	canAttackOwnSummons = false
	#The maximum amount of times an applicable piece of equipment can be upgraded in the arcane anvil. Default: 3
	maxUpgrades = 3
	#From 0-1, the percent of max mana a player respawns with. Default: 0.0
	manaSpawnPercent = 0.0
	#From 0-1, the percent chance for scrolls to be successfully recycled. Default: 0.5 (50%)
	scrollRecycleChance = 0.5
	#Whether or not potions should be allowed to be brewed in the alchemist cauldron)
	allowCauldronBrewing = true
	#Whether or not Furled Map items should skip chunks when searching for structures (only find new structures). Can impact performance while searching. Default: true
	furledMapSkipsExistingChunks = true
	#Whether or not casting items should apply all attributes while in the offhand, or just magic related ones. Default: true
	applyAllMultihandAttributes = true
	#Whether or not creepers should be healed and become fire immune when struck by lightning. Default: true
	betterCreeperThunderHit = true
	#Whether or not spells such as Fireball or Fire Breath should destroy terrain or create fire. Default: false
	spellGriefing = false
	#Whether or not the wandering trader can have magic related trades, such as ink or scrolls. Default: true
	additionalWanderingTraderTrades = true
	#Whether casting spells should be disabled in adventure mode. Default: false
	disableAdventureModeCasting = false
	#Whether hoglins have the ability to pass overworld zombification immunity to their offspring. Default: true
	hoglinOffspringProtection = true
	#Global multiplier to all players' mana regeneration. Default: 1.0
	manaRegenMultiplier = 1.0
	#Whether merging scrolls with ink to upgrade them in the Arcane Anvil is enabled.
	scrollMerging = true
	#Whether mana is required in creative mode. Default: false
	creativeMana = false
	#Whether cooldowns are respected in creative mode. Default: false
	creativeCooldowns = false

["Upgrade Overrides"]
	#Use these lists to change what items can interact with the Arcane Anvil's upgrade system. This can also be done via datapack.
	#Upgrade Whitelist. Use an item's id to allow it to be upgraded, ex: "minecraft:iron_sword"
	upgradeWhitelist = []
	#Upgrade Blacklist. Use an item's id to prevent it from being upgraded, ex: "minecraft:iron_sword"
	upgradeBlacklist = []

["Imbue Overrides"]
	#Use these lists to change what items can interact with the Arcane Anvil's imbue system.
	#/!\ Unsupported item types are not guaranteed to work out of the box.
	#Imbue Whitelist. Use an item's id to allow it to be imbued, ex: "minecraft:iron_sword"
	imbueWhitelist = []
	#Imbue Blacklist. Use an item's id to prevent it from being imbued, ex: "minecraft:iron_sword"
	imbueBlacklist = []

[Worldgen]
	#The weight of the priest house spawning in a village. Default: 4
	priestHouseWeight = 4
	#Whether to prevent aquifers from intersecting designated underground structures. May affect performance. Default: true
	aquiferDetection = true
	#Whether to enabled Ice Spider patrols in snowy biomes during snowy weather. Default: true
	iceSpiderPatrols = true

	#Configure Boss Stats
	["Boss Config".Tyros]
		#Additional Health
		additionalHealth = 0.0
		#Additional Melee Attack Damage
		additionalAttackDamage = 0.0
		#Additional Spell Power (additive percent)
		additionalSpellPower = 0.0

#Other Configuration
[Blocks]
	#Whether Portal Frames can only be dyed by the block's owner. Default: true
	portalFrameRestrictDye = true
	#Whether Portal Frames can only be destroyed by the block's owner. Default: false
	portalFrameRestrictBreaking = false
