[textures]
	#configuration options for textures
	#set to true to use vanilla textures instead of Lootr special textures. Note: this will prevent previously opened chests from rendering differently
	vanilla_textures = false
	#set to true to use the new Lootr textures
	new_textures = false

[particles]
	#configuration options for particles
	#set to true to enable 'unopened particles' to spawn from containers that the player has not yet opened
	unopened_particles = true
