[codex]
	#What theme should the encyclopedia arcana be in?
	#Allowed Values: DEFAULT, EASY_READING
	bookTheme = "DEFAULT"
	#Should the scroll direction be reversed in the encyclopedia arcana entry screen? This simply affects how you move through pages in an entry.
	scrollDirection = false

[scarf]
	#How long should the Malignant Stronghold Scarf be? This value will affect all rendered scarves, not just the one worn by the local player.
	scarfLength = 30
	#How visible. should the Malignant Stronghold Scarf be in first person?
	scarfOpacity = 0.4

[ui]
	#X offset from the center of the screen for the Soul Ward and Malignant Aegis HUD Elements.
	shieldX = 0
	#Y offset from the bottom of the screen for the Soul Ward and Malignant Aegis HUD Elements.
	shieldY = 47

[renderpass]
	#Enable or disable the parallel world renderer, used for various effects related to a certain feature. Disable if it causes framerate issues.
	renderParallelWorld = true
